version: "3.9"
services:
  rhymix:
      build: ./
      volumes:
          - ../:/var/www/html
      ports:
          - '80:80'
      depends_on:
          - mysql
  mysql:
      image: mysql:5.6.40
      ports:
          - "3306:3306"
      environment:
          - MYSQL_DATABASE=rhymix
          - MYSQL_USER=rhymix
          - MYSQL_PASSWORD=rhymix
          - MYSQL_ROOT_PASSWORD=mysql-root

  # 라이선스 동의화면을 거치지 않고 진입하는 경우 세션 오류가 표시됩니다. install.controller.php L321 참고.
  # 설치시 MySQL host를 mysql 로 설정합니다.
